/**
 * CarbonAware.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CarbonIntensityDTO {
    /**
    * the location name where workflow is run
    */
    'location'?: string | null;
    /**
    * the time at which the workflow we are measuring carbon intensity for started
    */
    'startTime'?: Date | null;
    /**
    * the time at which the workflow we are measuring carbon intensity for ended
    */
    'endTime'?: Date | null;
    /**
    * Value of the marginal carbon intensity in grams per kilowatt-hour.
    */
    'carbonIntensity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date"
        },
        {
            "name": "carbonIntensity",
            "baseName": "carbonIntensity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CarbonIntensityDTO.attributeTypeMap;
    }
}

