/**
 * CarbonAware.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmissionsDataDTO } from './emissionsDataDTO';

export class EmissionsForecastDTO {
    /**
    * Timestamp when the forecast was generated.
    */
    'generatedAt'?: Date;
    /**
    * For current requests, this value is the timestamp the request for forecast data was made.  For historical forecast requests, this value is the timestamp used to access the most   recently generated forecast as of that time.
    */
    'requestedAt'?: Date;
    /**
    * The location of the forecast
    */
    'location'?: string | null;
    /**
    * Start time boundary of forecasted data points. Ignores forecast data points before this time.  Defaults to the earliest time in the forecast data.
    */
    'dataStartAt'?: Date;
    /**
    * End time boundary of forecasted data points. Ignores forecast data points after this time.  Defaults to the latest time in the forecast data.
    */
    'dataEndAt'?: Date;
    /**
    * The estimated duration (in minutes) of the workload.  Defaults to the duration of a single forecast data point.
    */
    'windowSize'?: number;
    /**
    * The optimal forecasted data point within the \'forecastData\' array.  Null if \'forecastData\' array is empty.
    */
    'optimalDataPoints'?: Array<EmissionsDataDTO> | null;
    /**
    * The forecasted data points transformed and filtered to reflect the specified time and window parameters.  Points are ordered chronologically; Empty array if all data points were filtered out.  E.G. dataStartAt and dataEndAt times outside the forecast period; windowSize greater than total duration of forecast data;
    */
    'forecastData'?: Array<EmissionsDataDTO> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generatedAt",
            "baseName": "generatedAt",
            "type": "Date"
        },
        {
            "name": "requestedAt",
            "baseName": "requestedAt",
            "type": "Date"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "dataStartAt",
            "baseName": "dataStartAt",
            "type": "Date"
        },
        {
            "name": "dataEndAt",
            "baseName": "dataEndAt",
            "type": "Date"
        },
        {
            "name": "windowSize",
            "baseName": "windowSize",
            "type": "number"
        },
        {
            "name": "optimalDataPoints",
            "baseName": "optimalDataPoints",
            "type": "Array<EmissionsDataDTO>"
        },
        {
            "name": "forecastData",
            "baseName": "forecastData",
            "type": "Array<EmissionsDataDTO>"
        }    ];

    static getAttributeTypeMap() {
        return EmissionsForecastDTO.attributeTypeMap;
    }
}

