/**
 * CarbonAware.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models'

export class EmissionsDataDTO {
  'location'?: string | null
  'timestamp'?: Date
  'duration'?: number
  'value'?: number

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'location',
      baseName: 'location',
      type: 'string',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'Date',
    },
    {
      name: 'duration',
      baseName: 'duration',
      type: 'number',
    },
    {
      name: 'value',
      baseName: 'value',
      type: 'number',
    },
  ]

  static getAttributeTypeMap() {
    return EmissionsDataDTO.attributeTypeMap
  }
}
