/**
 * CarbonAware.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models'

export class EmissionsForecastBatchParametersDTO {
  /**
   * For historical forecast requests, this value is the timestamp used to access the most  recently generated forecast as of that time.
   */
  'requestedAt'?: Date | null
  /**
   * The location of the forecast
   */
  'location'?: string | null
  /**
   * Start time boundary of forecasted data points.Ignores current forecast data points before this time.  Defaults to the earliest time in the forecast data.
   */
  'dataStartAt'?: Date | null
  /**
   * End time boundary of forecasted data points. Ignores current forecast data points after this time.  Defaults to the latest time in the forecast data.
   */
  'dataEndAt'?: Date | null
  /**
   * The estimated duration (in minutes) of the workload.  Defaults to the duration of a single forecast data point.
   */
  'windowSize'?: number | null

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'requestedAt',
      baseName: 'requestedAt',
      type: 'Date',
    },
    {
      name: 'location',
      baseName: 'location',
      type: 'string',
    },
    {
      name: 'dataStartAt',
      baseName: 'dataStartAt',
      type: 'Date',
    },
    {
      name: 'dataEndAt',
      baseName: 'dataEndAt',
      type: 'Date',
    },
    {
      name: 'windowSize',
      baseName: 'windowSize',
      type: 'number',
    },
  ]

  static getAttributeTypeMap() {
    return EmissionsForecastBatchParametersDTO.attributeTypeMap
  }
}
