/**
 * CarbonAware.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models'

export class ValidationProblemDetails extends null<string, any> {
  'type'?: string | null
  'title'?: string | null
  'status'?: number | null
  'detail'?: string | null
  'instance'?: string | null
  'errors'?: { [key: string]: Array<string> } | null

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'number',
    },
    {
      name: 'detail',
      baseName: 'detail',
      type: 'string',
    },
    {
      name: 'instance',
      baseName: 'instance',
      type: 'string',
    },
    {
      name: 'errors',
      baseName: 'errors',
      type: '{ [key: string]: Array<string>; }',
    },
  ]

  static getAttributeTypeMap() {
    return super
      .getAttributeTypeMap()
      .concat(ValidationProblemDetails.attributeTypeMap)
  }
}
